from pathlib import Path


MYSQL_DEFAULT_DATABASE = "sakila"

MYSQL_DEFAULT_PORT = 3306

MYSQL_DRIVERNAME = "mysql+mysqldb"

MYSQL_DOTENV_USER = "MYSQL_USER"

MYSQL_DOTENV_PASSWORD = "MYSQL_PASSWD"

MYSQL_DOTENV_PORT = "MYSQL_PORT"

MYSQL_DOTENV_DATABASE = "MYSQL_DATABASE"
